# Generated by Django 5.2.5 on 2026-05-25 01:56

import django.db.models.deletion
from django.conf import settings
from django.db import migrations, models


class Migration(migrations.Migration):

    initial = True

    dependencies = [
        migrations.swappable_dependency(settings.AUTH_USER_MODEL),
    ]

    operations = [
        migrations.CreateModel(
            name='UserProfile',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('middle_name', models.CharField(blank=True, default='', max_length=100)),
                ('position', models.CharField(blank=True, default='', max_length=150, verbose_name='Position/Designation')),
                ('role', models.CharField(choices=[('administrator', 'Administrator'), ('co_employee', 'CO Employee'), ('wiki_moderator', 'Wiki Moderator'), ('ro_employee', 'RO Employee'), ('hospital_employee', 'Hospital Employee'), ('coop_staff', 'COOP Staff')], default='hospital_employee', max_length=30)),
                ('avatar', models.ImageField(blank=True, null=True, upload_to='avatars/')),
                ('user', models.OneToOneField(on_delete=django.db.models.deletion.CASCADE, related_name='profile', to=settings.AUTH_USER_MODEL)),
            ],
        ),
    ]
