# Generated by Django 5.2.5 on 2026-05-25 03:35

import django.db.models.deletion
from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('intranetapp', '0001_initial'),
    ]

    operations = [
        migrations.CreateModel(
            name='ModulePermission',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('press_releases', models.BooleanField(default=False)),
                ('events_trainings', models.BooleanField(default=False)),
                ('issuances', models.BooleanField(default=False)),
                ('wiki', models.BooleanField(default=False)),
                ('employees_corner', models.BooleanField(default=False)),
                ('applications', models.BooleanField(default=False)),
                ('directory', models.BooleanField(default=False)),
                ('downloads', models.BooleanField(default=False)),
                ('user_management', models.BooleanField(default=False)),
                ('profile', models.OneToOneField(on_delete=django.db.models.deletion.CASCADE, related_name='module_permissions', to='intranetapp.userprofile')),
            ],
        ),
    ]
