# Generated by Django 5.2.5 on 2026-05-25 06:50

import django.db.models.deletion
from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('intranetapp', '0002_modulepermission'),
    ]

    operations = [
        migrations.CreateModel(
            name='Role',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('name', models.CharField(max_length=100, unique=True)),
                ('press_releases', models.BooleanField(default=False)),
                ('events_trainings', models.BooleanField(default=False)),
                ('issuances', models.BooleanField(default=False)),
                ('wiki', models.BooleanField(default=False)),
                ('employees_corner', models.BooleanField(default=False)),
                ('applications', models.BooleanField(default=False)),
                ('directory', models.BooleanField(default=False)),
                ('downloads', models.BooleanField(default=False)),
                ('user_management', models.BooleanField(default=False)),
                ('created_at', models.DateTimeField(auto_now_add=True)),
                ('updated_at', models.DateTimeField(auto_now=True)),
            ],
            options={
                'ordering': ['name'],
            },
        ),
        migrations.AlterField(
            model_name='userprofile',
            name='role',
            field=models.ForeignKey(blank=True, null=True, on_delete=django.db.models.deletion.SET_NULL, related_name='userprofile_set', to='intranetapp.role'),
        ),
        migrations.DeleteModel(
            name='ModulePermission',
        ),
    ]
