# Generated by Django 5.2.5 on 2026-05-25 07:09

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('intranetapp', '0003_role_alter_userprofile_role_delete_modulepermission'),
    ]

    operations = [
        migrations.AddField(
            model_name='role',
            name='description',
            field=models.TextField(blank=True, default=''),
        ),
    ]
