# Generated by Django 5.2.5 on 2026-05-26 02:15

import django.db.models.deletion
from django.conf import settings
from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('intranetapp', '0004_role_description'),
        migrations.swappable_dependency(settings.AUTH_USER_MODEL),
    ]

    operations = [
        migrations.CreateModel(
            name='PressRelease',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('title', models.CharField(max_length=300)),
                ('slug', models.SlugField(blank=True, max_length=320, unique=True)),
                ('details', models.TextField()),
                ('image', models.ImageField(blank=True, null=True, upload_to='press_releases/')),
                ('status', models.CharField(choices=[('draft', 'Draft'), ('published', 'Published'), ('archived', 'Archived')], default='draft', max_length=20)),
                ('archive_policy', models.CharField(choices=[('default', 'Use Default Policy'), ('on_date', 'Archive on specific date'), ('never', 'Do not archive')], default='default', max_length=20)),
                ('archive_date', models.DateField(blank=True, help_text='Only used when archive_policy = on_date', null=True)),
                ('created_at', models.DateTimeField(auto_now_add=True)),
                ('updated_at', models.DateTimeField(auto_now=True)),
                ('published_at', models.DateTimeField(blank=True, null=True)),
                ('author', models.ForeignKey(blank=True, null=True, on_delete=django.db.models.deletion.SET_NULL, related_name='press_releases', to=settings.AUTH_USER_MODEL)),
            ],
            options={
                'verbose_name': 'Press Release',
                'verbose_name_plural': 'Press Releases',
                'ordering': ['-created_at'],
            },
        ),
    ]
