# Generated by Django 5.2.5 on 2026-05-28 01:59

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('intranetapp', '0007_training_trainingattachment'),
    ]

    operations = [
        migrations.AddField(
            model_name='userprofile',
            name='department',
            field=models.CharField(blank=True, choices=[('', '— Select a department —'), ('Medical Service', 'Medical Service'), ('Allied Health Professional Service', 'Allied Health Professional Service'), ('Nursing Service', 'Nursing Service'), ('Hospital Operations and Patient Support Services', 'Hospital Operations and Patient Support Services'), ('Finance Service', 'Finance Service')], default='', max_length=200, verbose_name='Department'),
        ),
    ]
