# Generated by Django 5.2.5 on 2026-05-28 02:50

import django.db.models.deletion
from django.conf import settings
from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('intranetapp', '0008_userprofile_department'),
        migrations.swappable_dependency(settings.AUTH_USER_MODEL),
    ]

    operations = [
        migrations.CreateModel(
            name='IssuanceCategory',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('name', models.CharField(max_length=200, unique=True)),
                ('created_at', models.DateTimeField(auto_now_add=True)),
                ('updated_at', models.DateTimeField(auto_now=True)),
            ],
            options={
                'verbose_name': 'Issuance Category',
                'verbose_name_plural': 'Issuance Categories',
                'ordering': ['name'],
            },
        ),
        migrations.AlterField(
            model_name='userprofile',
            name='department',
            field=models.CharField(blank=True, choices=[('Medical Service', 'Medical Service'), ('Allied Health Professional Service', 'Allied Health Professional Service'), ('Nursing Service', 'Nursing Service'), ('Hospital Operations and Patient Support Services', 'Hospital Operations and Patient Support Services'), ('Finance Service', 'Finance Service')], default='', max_length=200, verbose_name='Department'),
        ),
        migrations.CreateModel(
            name='Issuance',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('issuance_no', models.CharField(help_text='Unique reference number, e.g. AO-2024-001', max_length=200, verbose_name='Issuance No.')),
                ('issuance_date', models.DateField(verbose_name='Issuance Date')),
                ('summary', models.TextField(verbose_name='Summary')),
                ('attachment', models.FileField(blank=True, null=True, upload_to='issuances/', verbose_name='Attachment')),
                ('status', models.CharField(choices=[('draft', 'Draft'), ('published', 'Published'), ('archived', 'Archived')], default='draft', max_length=20)),
                ('archive_policy', models.CharField(choices=[('default', 'Use Default Policy'), ('on_date', 'Archive on specific date'), ('never', 'Do not archive')], default='default', max_length=20)),
                ('archive_date', models.DateField(blank=True, help_text='Only used when archive_policy = on_date', null=True)),
                ('created_at', models.DateTimeField(auto_now_add=True)),
                ('updated_at', models.DateTimeField(auto_now=True)),
                ('published_at', models.DateTimeField(blank=True, null=True)),
                ('author', models.ForeignKey(blank=True, null=True, on_delete=django.db.models.deletion.SET_NULL, related_name='issuances', to=settings.AUTH_USER_MODEL)),
                ('category', models.ForeignKey(on_delete=django.db.models.deletion.PROTECT, related_name='issuances', to='intranetapp.issuancecategory', verbose_name='Category')),
            ],
            options={
                'verbose_name': 'Issuance',
                'verbose_name_plural': 'Issuances',
                'ordering': ['-issuance_date', '-created_at'],
            },
        ),
    ]
