# Generated by Django 5.2.5 on 2026-05-28 03:57

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('intranetapp', '0009_issuancecategory_alter_userprofile_department_and_more'),
    ]

    operations = [
        migrations.AddField(
            model_name='role',
            name='role_management',
            field=models.CharField(choices=[('none', 'None'), ('view', 'View Only'), ('edit', 'Edit')], default='none', max_length=10),
        ),
        migrations.AddField(
            model_name='role',
            name='settings',
            field=models.CharField(choices=[('none', 'None'), ('view', 'View Only'), ('edit', 'Edit')], default='none', max_length=10),
        ),
        migrations.AlterField(
            model_name='role',
            name='applications',
            field=models.CharField(choices=[('none', 'None'), ('view', 'View Only'), ('edit', 'Edit')], default='none', max_length=10),
        ),
        migrations.AlterField(
            model_name='role',
            name='directory',
            field=models.CharField(choices=[('none', 'None'), ('view', 'View Only'), ('edit', 'Edit')], default='none', max_length=10),
        ),
        migrations.AlterField(
            model_name='role',
            name='downloads',
            field=models.CharField(choices=[('none', 'None'), ('view', 'View Only'), ('edit', 'Edit')], default='none', max_length=10),
        ),
        migrations.AlterField(
            model_name='role',
            name='employees_corner',
            field=models.CharField(choices=[('none', 'None'), ('view', 'View Only'), ('edit', 'Edit')], default='none', max_length=10),
        ),
        migrations.AlterField(
            model_name='role',
            name='events_trainings',
            field=models.CharField(choices=[('none', 'None'), ('view', 'View Only'), ('edit', 'Edit')], default='none', max_length=10),
        ),
        migrations.AlterField(
            model_name='role',
            name='issuances',
            field=models.CharField(choices=[('none', 'None'), ('view', 'View Only'), ('edit', 'Edit')], default='none', max_length=10),
        ),
        migrations.AlterField(
            model_name='role',
            name='press_releases',
            field=models.CharField(choices=[('none', 'None'), ('view', 'View Only'), ('edit', 'Edit')], default='none', max_length=10),
        ),
        migrations.AlterField(
            model_name='role',
            name='user_management',
            field=models.CharField(choices=[('none', 'None'), ('view', 'View Only'), ('edit', 'Edit')], default='none', max_length=10),
        ),
        migrations.AlterField(
            model_name='role',
            name='wiki',
            field=models.CharField(choices=[('none', 'None'), ('view', 'View Only'), ('edit', 'Edit')], default='none', max_length=10),
        ),
    ]
