# Generated by Django 5.2.5 on 2026-05-29 07:08

import django.db.models.deletion
from django.conf import settings
from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('intranetapp', '0011_add_e_library_field'),
        migrations.swappable_dependency(settings.AUTH_USER_MODEL),
    ]

    operations = [
        migrations.CreateModel(
            name='WikiTag',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('name', models.CharField(max_length=100, unique=True)),
                ('created_at', models.DateTimeField(auto_now_add=True)),
                ('updated_at', models.DateTimeField(auto_now=True)),
            ],
            options={
                'verbose_name': 'Wiki Tag',
                'verbose_name_plural': 'Wiki Tags',
                'ordering': ['name'],
            },
        ),
        migrations.CreateModel(
            name='WikiArticle',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('title', models.CharField(max_length=300, verbose_name='Title')),
                ('article', models.TextField(verbose_name='Article')),
                ('reference', models.CharField(help_text='e.g. RA 11032, Section 4 / https://...', max_length=500, verbose_name='Reference')),
                ('status', models.CharField(choices=[('draft', 'Draft'), ('published', 'Published'), ('archived', 'Archived')], default='draft', max_length=20)),
                ('archive_policy', models.CharField(choices=[('default', 'Use Default Policy'), ('on_date', 'Archive on specific date'), ('never', 'Do not archive')], default='default', max_length=20)),
                ('archive_date', models.DateField(blank=True, help_text='Only used when archive_policy = on_date', null=True)),
                ('created_at', models.DateTimeField(auto_now_add=True)),
                ('updated_at', models.DateTimeField(auto_now=True)),
                ('published_at', models.DateTimeField(blank=True, null=True)),
                ('author', models.ForeignKey(blank=True, null=True, on_delete=django.db.models.deletion.SET_NULL, related_name='wiki_articles', to=settings.AUTH_USER_MODEL)),
                ('tags', models.ManyToManyField(blank=True, related_name='wiki_articles', to='intranetapp.wikitag', verbose_name='Tags')),
            ],
            options={
                'verbose_name': 'Wiki Article',
                'verbose_name_plural': 'Wiki Articles',
                'ordering': ['-created_at'],
            },
        ),
    ]
