# Generated by Django on 2026-05-29 00:00

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('intranetapp', '0013_userprofile_bio_userprofile_gender_and_more'),
    ]

    operations = [
        migrations.AddField(
            model_name='userprofile',
            name='gender_self_describe',
            field=models.CharField(blank=True, default='', max_length=100, verbose_name='Gender Self Description'),
        ),
    ]
