# Generated by Django 5.2.5 on 2026-06-01 03:10

import django.db.models.deletion
from django.conf import settings
from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('intranetapp', '0014_userprofile_gender_self_describe'),
        migrations.swappable_dependency(settings.AUTH_USER_MODEL),
    ]

    operations = [
        migrations.CreateModel(
            name='EmployeeCornerPost',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('title', models.CharField(max_length=300)),
                ('summary', models.CharField(blank=True, default='', max_length=500)),
                ('content', models.TextField()),
                ('category', models.CharField(choices=[('union', 'Union'), ('coop', 'Cooperative')], default='union', max_length=20)),
                ('status', models.CharField(choices=[('draft', 'Draft'), ('published', 'Published'), ('archived', 'Archived')], default='draft', max_length=20)),
                ('date_posted', models.DateField()),
                ('archive_policy', models.CharField(choices=[('default', 'Use Default Policy'), ('on_date', 'Archive on specific date'), ('never', 'Do not archive')], default='default', max_length=20)),
                ('archive_date', models.DateField(blank=True, help_text='Only used when archive_policy = on_date', null=True)),
                ('created_at', models.DateTimeField(auto_now_add=True)),
                ('updated_at', models.DateTimeField(auto_now=True)),
                ('published_at', models.DateTimeField(blank=True, null=True)),
                ('author', models.ForeignKey(blank=True, null=True, on_delete=django.db.models.deletion.SET_NULL, related_name='employee_corner_posts', to=settings.AUTH_USER_MODEL)),
            ],
            options={
                'verbose_name': 'Employee Corner Post',
                'verbose_name_plural': 'Employee Corner Posts',
                'ordering': ['-date_posted', '-created_at'],
            },
        ),
        migrations.CreateModel(
            name='PostAttachment',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('file', models.FileField(upload_to='employee_corner_attachments/')),
                ('original_name', models.CharField(max_length=255)),
                ('uploaded_at', models.DateTimeField(auto_now_add=True)),
                ('post', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, related_name='attachments', to='intranetapp.employeecornerpost')),
            ],
            options={
                'verbose_name': 'Post Attachment',
                'verbose_name_plural': 'Post Attachments',
                'ordering': ['-uploaded_at'],
            },
        ),
    ]
