# Generated by Django 5.2.5 on 2026-06-02 01:25

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('intranetapp', '0016_application'),
    ]

    operations = [
        migrations.AlterField(
            model_name='userprofile',
            name='department',
            field=models.CharField(blank=True, choices=[('Office of the Medical Center Chief — Legal Unit', 'Legal Unit (MCC Office)'), ('Office of the Medical Center Chief — Public Health Unit', 'Public Health Unit (MCC Office)'), ('Office of the Medical Center Chief — Planning and Management Unit', 'Planning and Management Unit (MCC Office)'), ('Office of the Medical Center Chief — Office of Strategic Management', 'Office of Strategic Management (MCC Office)'), ('Office of the Medical Center Chief — Professional Education, Training and Research', 'Professional Education, Training and Research (MCC Office)'), ('Office of the Medical Center Chief — Health Emergency and Disaster Management Unit', 'Health Emergency and Disaster Management Unit (MCC Office)'), ('Allied Health Professional Service — Nutrition and Dietetics Department', 'Nutrition and Dietetics Department'), ('Allied Health Professional Service — Pharmacy Department', 'Pharmacy Department'), ('Allied Health Professional Service — Medical Social Work Department', 'Medical Social Work Department'), ('Allied Health Professional Service — Health Information Management Department', 'Health Information Management Department'), ('Nursing Service — Clinical Nursing Units', 'Clinical Nursing Units'), ('Nursing Service — Operating Room', 'Operating Room'), ('Nursing Service — Special Care Areas', 'Special Care Areas'), ('Nursing Service — Obstetric Complex', 'Obstetric Complex'), ('Nursing Service — Emergency Room', 'Emergency Room'), ('Nursing Service — Outpatient Department', 'Outpatient Department'), ('Nursing Service — Dialysis Unit', 'Dialysis Unit'), ('HOPSS — Human Resource Management Section', 'Human Resource Management Section'), ('HOPSS — Procurement Section', 'Procurement Section'), ('HOPSS — Materials Management Section', 'Materials Management Section'), ('HOPSS — Integrated Management Information System Section', 'Integrated Management Information System Section'), ('HOPSS — Security', 'Security'), ('HOPSS — Engineering and Facilities Management Section', 'Engineering and Facilities Management Section'), ('HOPSS — Housekeeping, Linen, and Laundry', 'Housekeeping, Linen, and Laundry'), ('Finance Service — Billing and Claims Section', 'Billing and Claims Section'), ('Finance Service — Accounting Section', 'Accounting Section'), ('Finance Service — Budget Section', 'Budget Section'), ('Finance Service — Cash Operations Section', 'Cash Operations Section'), ('Finance Service — Health Insurance Medical Evaluation Unit', 'Health Insurance Medical Evaluation Unit')], default='', max_length=200, verbose_name='Department'),
        ),
    ]
