# Generated by Django 5.2.5 on 2026-06-02 02:31

import django.db.models.deletion
from django.conf import settings
from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('intranetapp', '0018_office'),
        migrations.swappable_dependency(settings.AUTH_USER_MODEL),
    ]

    operations = [
        migrations.CreateModel(
            name='DownloadCategory',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('name', models.CharField(max_length=200, unique=True)),
                ('tab', models.CharField(choices=[('forms', 'Forms'), ('files', 'Files')], default='forms', max_length=10)),
                ('created_at', models.DateTimeField(auto_now_add=True)),
                ('updated_at', models.DateTimeField(auto_now=True)),
            ],
            options={
                'verbose_name': 'Download Category',
                'verbose_name_plural': 'Download Categories',
                'ordering': ['tab', 'name'],
            },
        ),
        migrations.CreateModel(
            name='DownloadTag',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('name', models.CharField(max_length=100, unique=True)),
                ('created_at', models.DateTimeField(auto_now_add=True)),
            ],
            options={
                'verbose_name': 'Download Tag',
                'verbose_name_plural': 'Download Tags',
                'ordering': ['name'],
            },
        ),
        migrations.CreateModel(
            name='Download',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('title', models.CharField(max_length=300)),
                ('tab', models.CharField(choices=[('forms', 'Forms'), ('files', 'Files')], db_index=True, default='forms', max_length=10)),
                ('attachment', models.FileField(upload_to='downloads/')),
                ('status', models.CharField(choices=[('draft', 'Draft'), ('published', 'Published'), ('archived', 'Archived')], default='draft', max_length=20)),
                ('archive_policy', models.CharField(choices=[('default', 'Use Default Policy'), ('on_date', 'Archive on specific date'), ('never', 'Do not archive')], default='default', max_length=20)),
                ('archive_date', models.DateField(blank=True, null=True)),
                ('created_at', models.DateTimeField(auto_now_add=True)),
                ('updated_at', models.DateTimeField(auto_now=True)),
                ('published_at', models.DateTimeField(blank=True, null=True)),
                ('author', models.ForeignKey(blank=True, null=True, on_delete=django.db.models.deletion.SET_NULL, related_name='downloads', to=settings.AUTH_USER_MODEL)),
                ('category', models.ForeignKey(on_delete=django.db.models.deletion.PROTECT, related_name='downloads', to='intranetapp.downloadcategory')),
                ('tags', models.ManyToManyField(blank=True, related_name='downloads', to='intranetapp.downloadtag')),
            ],
            options={
                'verbose_name': 'Download',
                'verbose_name_plural': 'Downloads',
                'ordering': ['-created_at'],
            },
        ),
    ]
