# Generated by Django 5.2.5 on 2026-06-22 06:00

from django.conf import settings
from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('intranetapp', '0028_message_is_system_alter_message_sender'),
        migrations.swappable_dependency(settings.AUTH_USER_MODEL),
    ]

    operations = [
        migrations.AddField(
            model_name='message',
            name='is_unsent',
            field=models.BooleanField(default=False),
        ),
        migrations.AddField(
            model_name='message',
            name='unsent_for',
            field=models.ManyToManyField(blank=True, related_name='hidden_messages', to=settings.AUTH_USER_MODEL),
        ),
    ]
