# Generated by Django 5.2.5 on 2026-06-24 04:04

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('intranetapp', '0029_message_is_unsent_message_unsent_for'),
    ]

    operations = [
        migrations.AddField(
            model_name='userprofile',
            name='access_reason',
            field=models.TextField(blank=True, default='', help_text='Filled in during registration; reviewed by IT before activation.', verbose_name='Reason for Access'),
        ),
    ]
