# Generated by Django 5.2.5 on 2026-07-22 07:51

import django.db.models.deletion
from django.conf import settings
from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('intranetapp', '0031_alter_userprofile_department'),
        migrations.swappable_dependency(settings.AUTH_USER_MODEL),
    ]

    operations = [
        migrations.AlterField(
            model_name='userprofile',
            name='department',
            field=models.CharField(blank=True, choices=[('Office of the Medical Center Chief', 'Office of the Medical Center Chief (Head Office)'), ('Office of the Medical Center Chief — Legal Unit', 'Legal Unit (MCC Office)'), ('Office of the Medical Center Chief — Public Health Unit', 'Public Health Unit (MCC Office)'), ('Office of the Medical Center Chief — Planning and Management Unit', 'Planning and Management Unit (MCC Office)'), ('Office of the Medical Center Chief — Office of Strategic Management', 'Office of Strategic Management (MCC Office)'), ('Office of the Medical Center Chief — Professional Education, Training and Research', 'Professional Education, Training and Research (MCC Office)'), ('Office of the Medical Center Chief — Health Emergency and Disaster Management Unit', 'Health Emergency and Disaster Management Unit (MCC Office)'), ('Office of the Medical Center Chief — Infection Prevention and Control Unit', 'Infection Prevention and Control Unit (MCC Office)'), ('Allied Health Professional Service', 'Office of the Chief Allied Health Professional Service (Head Office)'), ('Allied Health Professional Service — Nutrition and Dietetics Department', 'Nutrition and Dietetics Department'), ('Allied Health Professional Service — Pharmacy Department', 'Pharmacy Department'), ('Allied Health Professional Service — Medical Social Work Department', 'Medical Social Work Department'), ('Allied Health Professional Service — Health Information Management Department', 'Health Information Management Department'), ('Nursing Service', 'Office of the Chief Nurse (Head Office)'), ('Nursing Service — Clinical Nursing Units', 'Clinical Nursing Units'), ('Nursing Service — Operating Room', 'Operating Room'), ('Nursing Service — Special Care Areas', 'Special Care Areas'), ('Nursing Service — Obstetric Complex', 'Obstetric Complex'), ('Nursing Service — Emergency Room', 'Emergency Room'), ('Nursing Service — Outpatient Department', 'Outpatient Department'), ('Nursing Service — Dialysis Unit', 'Dialysis Unit'), ('HOPSS', 'Office of the Chief Administrative Officer (Head Office)'), ('HOPSS — Human Resource Management Section', 'Human Resource Management Section'), ('HOPSS — Procurement Section', 'Procurement Section'), ('HOPSS — Materials Management Section', 'Materials Management Section'), ('HOPSS — Integrated Management Information System Section', 'Integrated Management Information System Section'), ('HOPSS — Security', 'Security'), ('HOPSS — Engineering and Facilities Management Section', 'Engineering and Facilities Management Section'), ('HOPSS — Housekeeping, Linen, and Laundry', 'Housekeeping, Linen, and Laundry'), ('Finance Service', 'Office of the Chief Finance Officer (Head Office)'), ('Finance Service — Billing and Claims Section', 'Billing and Claims Section'), ('Finance Service — Accounting Section', 'Accounting Section'), ('Finance Service — Budget Section', 'Budget Section'), ('Finance Service — Cash Operations Section', 'Cash Operations Section'), ('Finance Service — Health Insurance Medical Evaluation Unit', 'Health Insurance Medical Evaluation Unit')], default='', max_length=200, verbose_name='Department'),
        ),
        migrations.CreateModel(
            name='PGSIndicator',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('department', models.CharField(choices=[('Office of the Medical Center Chief', 'Office of the Medical Center Chief (Head Office)'), ('Office of the Medical Center Chief — Legal Unit', 'Legal Unit (MCC Office)'), ('Office of the Medical Center Chief — Public Health Unit', 'Public Health Unit (MCC Office)'), ('Office of the Medical Center Chief — Planning and Management Unit', 'Planning and Management Unit (MCC Office)'), ('Office of the Medical Center Chief — Office of Strategic Management', 'Office of Strategic Management (MCC Office)'), ('Office of the Medical Center Chief — Professional Education, Training and Research', 'Professional Education, Training and Research (MCC Office)'), ('Office of the Medical Center Chief — Health Emergency and Disaster Management Unit', 'Health Emergency and Disaster Management Unit (MCC Office)'), ('Office of the Medical Center Chief — Infection Prevention and Control Unit', 'Infection Prevention and Control Unit (MCC Office)'), ('Allied Health Professional Service', 'Office of the Chief Allied Health Professional Service (Head Office)'), ('Allied Health Professional Service — Nutrition and Dietetics Department', 'Nutrition and Dietetics Department'), ('Allied Health Professional Service — Pharmacy Department', 'Pharmacy Department'), ('Allied Health Professional Service — Medical Social Work Department', 'Medical Social Work Department'), ('Allied Health Professional Service — Health Information Management Department', 'Health Information Management Department'), ('Nursing Service', 'Office of the Chief Nurse (Head Office)'), ('Nursing Service — Clinical Nursing Units', 'Clinical Nursing Units'), ('Nursing Service — Operating Room', 'Operating Room'), ('Nursing Service — Special Care Areas', 'Special Care Areas'), ('Nursing Service — Obstetric Complex', 'Obstetric Complex'), ('Nursing Service — Emergency Room', 'Emergency Room'), ('Nursing Service — Outpatient Department', 'Outpatient Department'), ('Nursing Service — Dialysis Unit', 'Dialysis Unit'), ('HOPSS', 'Office of the Chief Administrative Officer (Head Office)'), ('HOPSS — Human Resource Management Section', 'Human Resource Management Section'), ('HOPSS — Procurement Section', 'Procurement Section'), ('HOPSS — Materials Management Section', 'Materials Management Section'), ('HOPSS — Integrated Management Information System Section', 'Integrated Management Information System Section'), ('HOPSS — Security', 'Security'), ('HOPSS — Engineering and Facilities Management Section', 'Engineering and Facilities Management Section'), ('HOPSS — Housekeeping, Linen, and Laundry', 'Housekeeping, Linen, and Laundry'), ('Finance Service', 'Office of the Chief Finance Officer (Head Office)'), ('Finance Service — Billing and Claims Section', 'Billing and Claims Section'), ('Finance Service — Accounting Section', 'Accounting Section'), ('Finance Service — Budget Section', 'Budget Section'), ('Finance Service — Cash Operations Section', 'Cash Operations Section'), ('Finance Service — Health Insurance Medical Evaluation Unit', 'Health Insurance Medical Evaluation Unit')], max_length=200)),
                ('title', models.CharField(max_length=300, verbose_name='Target / Indicator')),
                ('description', models.TextField(blank=True, default='')),
                ('target_value', models.DecimalField(decimal_places=2, max_digits=14)),
                ('unit', models.CharField(default='%', help_text='e.g. %, files, positions, days', max_length=50)),
                ('is_archived', models.BooleanField(default=False)),
                ('created_at', models.DateTimeField(auto_now_add=True)),
                ('updated_at', models.DateTimeField(auto_now=True)),
                ('created_by', models.ForeignKey(blank=True, null=True, on_delete=django.db.models.deletion.SET_NULL, related_name='pgs_indicators', to=settings.AUTH_USER_MODEL)),
            ],
            options={
                'verbose_name': 'PGS Target',
                'verbose_name_plural': 'PGS Targets',
                'ordering': ['department', 'title'],
            },
        ),
        migrations.CreateModel(
            name='PGSProgressEntry',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('period', models.CharField(help_text='e.g. 2026-Q3, October 2026', max_length=50, verbose_name='Reporting Period')),
                ('actual_value', models.DecimalField(decimal_places=2, max_digits=14)),
                ('remarks', models.TextField(blank=True, default='')),
                ('attachment', models.FileField(blank=True, null=True, upload_to='pgs_attachments/', verbose_name='Supporting File')),
                ('submitted_at', models.DateTimeField(auto_now_add=True)),
                ('indicator', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, related_name='entries', to='intranetapp.pgsindicator')),
                ('submitted_by', models.ForeignKey(blank=True, null=True, on_delete=django.db.models.deletion.SET_NULL, related_name='pgs_entries', to=settings.AUTH_USER_MODEL)),
            ],
            options={
                'verbose_name': 'PGS Progress Entry',
                'verbose_name_plural': 'PGS Progress Entries',
                'ordering': ['-submitted_at'],
            },
        ),
    ]
