# Generated by Django on 2026-07-22 00:00

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('intranetapp', '0032_alter_userprofile_department_pgsindicator_and_more'),
    ]

    operations = [
        migrations.AddField(
            model_name='role',
            name='pgs',
            field=models.CharField(choices=[('none', 'None'), ('view', 'View Only'), ('edit', 'Edit')], default='none', max_length=10),
        ),
    ]
