# Generated by Django 5.2.5 on 2026-07-22 09:13

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('intranetapp', '0033_add_pgs_permission_to_role'),
    ]

    operations = [
        migrations.AlterModelOptions(
            name='pgsindicator',
            options={'ordering': ['department', 'title'], 'verbose_name': 'PGS Deliverable', 'verbose_name_plural': 'PGS Deliverables'},
        ),
        migrations.AlterModelOptions(
            name='pgsprogressentry',
            options={'ordering': ['-submitted_at'], 'verbose_name': 'PGS Progress Update', 'verbose_name_plural': 'PGS Progress Updates'},
        ),
        migrations.RemoveField(
            model_name='pgsindicator',
            name='target_value',
        ),
        migrations.RemoveField(
            model_name='pgsindicator',
            name='unit',
        ),
        migrations.RemoveField(
            model_name='pgsprogressentry',
            name='actual_value',
        ),
        migrations.RemoveField(
            model_name='pgsprogressentry',
            name='period',
        ),
        migrations.AddField(
            model_name='pgsindicator',
            name='due_date',
            field=models.DateField(blank=True, null=True, verbose_name='Due Date'),
        ),
        migrations.AddField(
            model_name='pgsprogressentry',
            name='percent_complete',
            field=models.DecimalField(decimal_places=2, default=0, max_digits=5, verbose_name='% Complete'),
            preserve_default=False,
        ),
        migrations.AlterField(
            model_name='pgsindicator',
            name='title',
            field=models.CharField(max_length=300, verbose_name='Deliverable'),
        ),
    ]
