# Generated by Django 5.2.5 on 2026-07-28 06:58

import django.db.models.deletion
from django.conf import settings
from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('intranetapp', '0035_pgsprogressentry_updated_at_and_more'),
        migrations.swappable_dependency(settings.AUTH_USER_MODEL),
    ]

    operations = [
        migrations.CreateModel(
            name='ELibraryCategory',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('name', models.CharField(max_length=200, unique=True)),
                ('created_at', models.DateTimeField(auto_now_add=True)),
                ('updated_at', models.DateTimeField(auto_now=True)),
            ],
            options={
                'verbose_name': 'e-Library Category',
                'verbose_name_plural': 'e-Library Categories',
                'ordering': ['name'],
            },
        ),
        migrations.CreateModel(
            name='ELibraryTag',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('name', models.CharField(max_length=100, unique=True)),
                ('created_at', models.DateTimeField(auto_now_add=True)),
            ],
            options={
                'verbose_name': 'e-Library Tag',
                'verbose_name_plural': 'e-Library Tags',
                'ordering': ['name'],
            },
        ),
        migrations.CreateModel(
            name='ELibraryItem',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('title', models.CharField(max_length=300)),
                ('material_type', models.CharField(choices=[('book', 'Book'), ('journal', 'Journal / Periodical'), ('thesis', 'Thesis / Research'), ('magazine', 'Magazine'), ('report', 'Institutional Report'), ('other', 'Other')], default='book', max_length=20, verbose_name='Material Type')),
                ('authors', models.CharField(blank=True, default='', max_length=500, verbose_name='Author(s)')),
                ('publisher', models.CharField(blank=True, default='', max_length=300)),
                ('publication_year', models.PositiveIntegerField(blank=True, null=True, verbose_name='Year Published')),
                ('edition', models.CharField(blank=True, default='', max_length=100)),
                ('isbn', models.CharField(blank=True, default='', max_length=50, verbose_name='ISBN / ISSN')),
                ('call_number', models.CharField(blank=True, default='', max_length=100, verbose_name='Call Number')),
                ('description', models.TextField(blank=True, default='', verbose_name='Abstract / Description')),
                ('cover_image', models.ImageField(blank=True, null=True, upload_to='e_library/covers/', verbose_name='Cover Image')),
                ('attachment', models.FileField(upload_to='e_library/files/', verbose_name='File')),
                ('status', models.CharField(choices=[('draft', 'Draft'), ('published', 'Published'), ('archived', 'Archived')], default='draft', max_length=20)),
                ('archive_policy', models.CharField(choices=[('default', 'Use Default Policy'), ('on_date', 'Archive on specific date'), ('never', 'Do not archive')], default='default', max_length=20)),
                ('archive_date', models.DateField(blank=True, help_text='Only used when archive_policy = on_date', null=True)),
                ('created_at', models.DateTimeField(auto_now_add=True)),
                ('updated_at', models.DateTimeField(auto_now=True)),
                ('published_at', models.DateTimeField(blank=True, null=True)),
                ('category', models.ForeignKey(on_delete=django.db.models.deletion.PROTECT, related_name='items', to='intranetapp.elibrarycategory', verbose_name='Category')),
                ('uploaded_by', models.ForeignKey(blank=True, null=True, on_delete=django.db.models.deletion.SET_NULL, related_name='e_library_items', to=settings.AUTH_USER_MODEL)),
                ('tags', models.ManyToManyField(blank=True, related_name='items', to='intranetapp.elibrarytag', verbose_name='Tags')),
            ],
            options={
                'verbose_name': 'e-Library Item',
                'verbose_name_plural': 'e-Library Items',
                'ordering': ['-created_at'],
            },
        ),
    ]
