# Generated by Django 5.2.5 on 2026-07-29 06:51

import django.db.models.deletion
from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('intranetapp', '0036_elibrarycategory_elibrarytag_elibraryitem'),
    ]

    operations = [
        migrations.CreateModel(
            name='ELibraryMaterialType',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('name', models.CharField(max_length=100, unique=True)),
                ('icon', models.CharField(blank=True, default='fa-file', help_text='Font Awesome class shown on cards, e.g. fa-book, fa-newspaper, fa-graduation-cap', max_length=50, verbose_name='Icon')),
                ('created_at', models.DateTimeField(auto_now_add=True)),
            ],
            options={
                'verbose_name': 'e-Library Material Type',
                'verbose_name_plural': 'e-Library Material Types',
                'ordering': ['name'],
            },
        ),
        migrations.AlterField(
            model_name='elibraryitem',
            name='material_type',
            field=models.ForeignKey(on_delete=django.db.models.deletion.PROTECT, related_name='items', to='intranetapp.elibrarymaterialtype', verbose_name='Material Type'),
        ),
    ]
