# Generated by Django 5.2.5 on 2026-08-04 02:42

import intranetapp.models
from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('intranetapp', '0039_message_edited_at_message_is_edited_messagereaction'),
    ]

    operations = [
        migrations.AddField(
            model_name='userprofile',
            name='quick_reactions',
            field=models.JSONField(default=intranetapp.models.default_quick_reactions),
        ),
    ]
