# Generated by Django 5.2.5 on 2026-08-17 06:09

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('intranetapp', '0040_userprofile_quick_reactions'),
    ]

    operations = [
        migrations.AddField(
            model_name='userprofile',
            name='is_head_of_office',
            field=models.BooleanField(default=False, help_text='Marks this person as the head of their department/office. Used to route email notifications (e.g. issuances) to office heads.', verbose_name='Head of Office'),
        ),
    ]
