# Generated by Django 5.2.5 on 2026-09-23 01:29

import django.db.models.deletion
from django.conf import settings
from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('intranetapp', '0042_downloadlog'),
        migrations.swappable_dependency(settings.AUTH_USER_MODEL),
    ]

    operations = [
        migrations.CreateModel(
            name='IssuanceView',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('viewed_at', models.DateTimeField(auto_now_add=True)),
                ('issuance', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, related_name='views', to='intranetapp.issuance')),
                ('user', models.ForeignKey(blank=True, null=True, on_delete=django.db.models.deletion.SET_NULL, related_name='issuance_views', to=settings.AUTH_USER_MODEL)),
            ],
            options={
                'verbose_name': 'Issuance View',
                'verbose_name_plural': 'Issuance Views',
                'ordering': ['-viewed_at'],
                'indexes': [models.Index(fields=['issuance', '-viewed_at'], name='intranetapp_issuanc_f1465d_idx')],
            },
        ),
    ]
